version: '3.1'

services:
  backend:
    image: 'dturysbay/message-handler-iso'
    container_name: 'message-handler-cont'
    depends_on:
      - pgdb
    environment:
      - SERVER_PORT=9999
      - SPRING_DATA_SOURCE=admin
      - SPRING_DATA_PASSWORD=admin
      - SPRING_DATA_URL=jdbc:postgresql://localhost:5432/postgres

    ports:
      - 8080:9999

  pgdb:
    image: postgres
    container_name: 'pg_container'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME : localhost
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181